services:
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: puretrace_broker
    ports:
      - "1883:1883" # Porta MQTT
      - "9001:9001" # Porta Websocket
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    restart: unless-stopped
